name: Driver
on: push
#on:
#  push:
#    paths:
#      - 'src/BlackBoneDrv/**'

jobs:
  driver:
    name: Build driver
    strategy:
      matrix:
        configuration: [Win10Debug, Win10Release, 'Win8.1 Debug', 'Win8.1 Release', 'Win8 Debug', 'Win8 Release', 'Win7 Debug', 'Win7 Release']
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && MSBuild.exe src\BlackBoneDrv\BlackBoneDrv.sln /p:Platform="x64" /p:Configuration="${{ matrix.configuration }}"
